"""
Django settings for miPrimerProyecto project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from pathlib import Path
from decouple import config
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'axes',       # bloqueo por intentos fallidos de login [OWASP 2.3]
    'usuarios',
    'parques',
    'reservaciones',
    'elProyecto',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

# [OWASP 2.3] Argon2 como hasher de contraseñas (más resistente a fuerza bruta que PBKDF2)
PASSWORD_HASHERS = ['django.contrib.auth.hashers.Argon2PasswordHasher']

# [OWASP 2.4] Seguridad de cookies de sesión
SESSION_COOKIE_HTTPONLY = True   # JavaScript no puede leer la cookie de sesión
SESSION_COOKIE_SAMESITE = 'Lax' # protege contra CSRF en requests cross-site
SESSION_COOKIE_AGE      = 3600  # sesión expira en 1 hora de inactividad
SESSION_COOKIE_SECURE   = not DEBUG  # True en prod (HTTPS), False en dev

# [OWASP 2.4] Seguridad de la cookie CSRF
CSRF_COOKIE_SECURE = not DEBUG  # True en prod (HTTPS), False en dev

# [OWASP 2.3] Bloqueo por intentos fallidos de login — django-axes
AXES_FAILURE_LIMIT    = 5    # bloquea después de 5 intentos fallidos
AXES_COOLOFF_TIME     = 1    # tiempo de bloqueo en horas
AXES_RESET_ON_SUCCESS = True # reinicia el contador si el login es exitoso

# django-axes requiere su propio backend antes del ModelBackend
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',        # intercepta antes de autenticar
    'django.contrib.auth.backends.ModelBackend',  # autenticación estándar de Django
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # registra intentos fallidos en la BD [OWASP 2.3]
]

ROOT_URLCONF = 'miPrimerProyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miPrimerProyecto.wsgi.application'


# Email — [OWASP 2.9] TLS obligatorio en prod
# Por defecto: console en dev (imprime en terminal), smtp en prod.
# Para enviar correos reales desde dev, agrega EMAIL_BACKEND=...smtp... en .env
_backend_default = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = env('EMAIL_BACKEND', default=_backend_default)
EMAIL_HOST          = env('EMAIL_HOST',          default='smtp.gmail.com')
EMAIL_PORT          = env.int('EMAIL_PORT',      default=587)
EMAIL_USE_TLS       = True                        # [OWASP 2.9] cifrado TLS obligatorio
EMAIL_HOST_USER     = env('EMAIL_HOST_USER',     default='')  # [OWASP 2.8] en .env, nunca hardcodeado
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')  # [OWASP 2.8] usar App Password de Gmail en prod
DEFAULT_FROM_EMAIL  = env('EMAIL_HOST_USER',     default='noreply@cepuac.mx')

# URL base del sitio — usada para construir enlaces en correos (recuperación, confirmación)
BASE_URL = env('BASE_URL', default='http://127.0.0.1:8000')


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE":   "django.db.backends.mysql",
        "NAME":     config("DB_NAME"),
        "USER":     config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST":     config("DB_HOST", default="localhost"),
        "PORT":     config("DB_PORT", default="3306"),
        "OPTIONS":  {"charset": "utf8mb4"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
