# Generated by Django 6.0.1 on 2026-05-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('numero_personas', models.PositiveIntegerField()),
                ('tipo_visita', models.CharField(choices=[('CABANA', 'Cabaña'), ('CAMPING', 'Camping')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reservación',
            },
        ),
    ]
