# Generated by Django 6.0.1 on 2026-05-18 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0002_remove_parque_capacidad_cabanas_marcador_cabana'),
        ('reservaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='cabana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='parques.cabana'),
        ),
    ]
