# Generated by Django 6.0.1 on 2026-05-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elProyecto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zapato',
        ),
    ]
