# Generated by Django 6.0.1 on 2026-05-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elProyecto', '0002_delete_zapato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('servicios', models.TextField(help_text='Servicios separados por coma')),
                ('horario', models.CharField(max_length=100)),
                ('tiene_cabana', models.BooleanField(default=False)),
            ],
        ),
    ]
