# Generated by Django 6.0.1 on 2026-05-18 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='capacidad_cabanas',
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('parque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marcador', to='parques.parque')),
            ],
            options={
                'verbose_name': 'marcador',
            },
        ),
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabanas', to='parques.parque')),
            ],
            options={
                'verbose_name': 'cabaña',
                'unique_together': {('parque', 'nombre')},
            },
        ),
    ]
