# Generated by Django 6.0.1 on 2026-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
